s1 <- sample(1:6, 40, replace = TRUE)
print(s1)
s2 <- sample(1:6, 70, replace = TRUE)
print(s2)
s3 <- sample(1:6, 100, replace = TRUE)
print(s3)
t <- table(s1) 
print(t)
#rank(t)
#order(t)
#length(t)
PD=table(s1)/length(s1)
print(PD)
#sum(PD)
barplot(t, main = "FREQUENCY S1", xlab = "Faces of dice", ylab = "Frequency",col =names(t))
t1 <- table(s2)
PD=t1/length(s2)
print(PD)
#sum(PD)
barplot(t1, main = "FREQUENCY S1", xlab = "Faces of dice", ylab = "Frequency",col =names(t1))
t2 <- table(s3)
PD=t2/length(s3)
print(PD)
#sum(PD)
barplot(t2, main = "FREQUENCY S1", xlab = "Faces of dice", ylab = "Frequency",col =names(t2))
plot(s1, main = "VALUES S1", xlab = "Index", ylab = "Faces of dice", col =s1)
plot(s2, main = "VALUES S2", xlab = "Index", ylab = "Faces of dice", col =s2)
plot(s3, main = "VALUES S3", xlab = "Index", ylab = "Faces of dice", col =s2)



