mode<-function(vec)
{
  t=table(vec)
  n=names(which(t==max(t)))
  return(n)
}

Age=c(20,20,20,20,20,21,21,21,22,22,22,22,23,23,23)
print(Age)
print("Find the median age of all students under 22 yrs")
print(median(Age[Age<22]))
print("Find the median age of all students")
print(median(Age))
print("Find the mean age of all students")
print(mean(Age))
print("find the modal age of all studnets")
print(mode(Age))

print("Two more students enter the class. The age of both studnets is 23")
Age1=c(Age,23,23)
print(Age1)
print("Find the median age of all students under 22 yrs")
print(median(Age1[Age1<22]))
print("Find the median age of all students")
print(median(Age1))
print("Find the mean age of all students")
print(mean(Age1))
print("find the modal age of all studnets")
print(mode(Age1))